# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: vkc
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_y_base_x
    - base_theta_base_y
    - base_link_base_theta
    - front_rocker
    - front_left_wheel
    - front_right_wheel
    - rear_left_wheel
    - rear_right_wheel
    - right_arm_shoulder_pan_joint
    - right_arm_shoulder_lift_joint
    - right_arm_elbow_joint
    - right_arm_wrist_1_joint
    - right_arm_wrist_2_joint
    - right_arm_wrist_3_joint
    - right_gripper_palm_finger_1_joint
    - right_gripper_finger_1_joint_1
    - right_gripper_finger_1_joint_2
    - right_gripper_finger_1_joint_3
    - right_gripper_palm_finger_2_joint
    - right_gripper_finger_2_joint_1
    - right_gripper_finger_2_joint_2
    - right_gripper_finger_2_joint_3
    - right_gripper_finger_middle_joint_1
    - right_gripper_finger_middle_joint_2
    - right_gripper_finger_middle_joint_3
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []